stages:
  - build

variables:
  REG_URL: ${CI_REGISTRY}/addev/${CI_PROJECT_NAME}
  APP_NAME: "newrelic-plugins"
  JAVA_OPTS: "-XX:MaxMetaspaceSize=512m -Xms1024m -Xmx2048m -Dsbt.override.build.repos=true -Dsbt.repository.config=repositories -Dsbt.global.staging=cache/.staging -Dsbt.ivy.home=cache/.ivy2/ -Divy.home=cache/.ivy2/"

non_master_build:
  stage: build
  except: 
    - master
    - tags
  tags:
    - docker
  image: gitlab.spice.spiceworks.com:4567/quentinc/centos-jdk8-ant:master
  cache:
    paths:
      - cache
  script:
    - ant dist
    - curl --netrc -X PUT https://spiceworks.jfrog.io/spiceworks/build-generic/newrelic-plugins/newrelic_3legs_plugin-3.1.0.tar.gz -T dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz
    - md5sum dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz >dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz.md5
    - curl --netrc -X PUT https://spiceworks.jfrog.io/spiceworks/build-generic/newrelic-plugins/newrelic_3legs_plugin-3.1.0.tar.gz.md5 -T dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz.md5

master_build:
  stage: build
  only:
    - master
    - tags
  tags:
    - docker
  image: gitlab.spice.spiceworks.com:4567/quentinc/centos-jdk8-ant:master
  cache:
    paths:
      - cache
  script:
    - ant dist

