stages:
  - build

variables:
  REG_URL: ${CI_REGISTRY}/addev/${CI_PROJECT_NAME}
  APP_NAME: "newrelic-plugins"
  JAVA_OPTS: "-XX:MaxMetaspaceSize=512m -Xms1024m -Xmx2048m -Dsbt.override.build.repos=true -Dsbt.repository.config=repositories -Dsbt.global.staging=cache/.staging -Dsbt.ivy.home=cache/.ivy2/ -Divy.home=cache/.ivy2/"

non_master_build:
  stage: build
  except: 
    - master
    - tags
  tags:
    - docker
  image: gitlab.spice.spiceworks.com:4567/quentinc/centos-jdk8-ant:master
  cache:
    paths:
      - cache
  script:
    - ant dist
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 2 week
    paths:
      - build/jar/plugin.jar
      - build/tar/newrelic_3legs_plugin-3.1.0/config/newrelic.template.json
      - build/tar/newrelic_3legs_plugin-3.1.0/config/plugin.template.json
      - dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz

master_build:
  stage: build
  only:
    - master
    - tags
  tags:
    - docker
  image: gitlab.spice.spiceworks.com:4567/quentinc/centos-jdk8-ant:master
  cache:
    paths:
      - cache
  script:
    - ant dist
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/jar/plugin.jar
      - build/tar/newrelic_3legs_plugin-3.1.0/config/newrelic.template.json
      - build/tar/newrelic_3legs_plugin-3.1.0/config/plugin.template.json
      - dist/3.1.0/newrelic_3legs_plugin-3.1.0.tar.gz

